name: smart_travel_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON Serialization
  json_annotation: ^4.8.1

  # UI & Icons
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    # destinations
    - assets/destinations/destination_0.png
    - assets/destinations/destination_1.png
    - assets/destinations/destination_2.png
    - assets/destinations/destination_3.png
    - assets/destinations/destination_4.png
    - assets/destinations/destination_5.png

    # icons
    - assets/icons/aeroplane.png
    - assets/icons/camp.png
    - assets/icons/suitcase.png
    - assets/profile.png

